### PR TITLE
CLI suport for parser

### PR DESCRIPTION
**Pull request by vigneshshanmugam**
Fixes #10

### CODE REVIEW

**Comment by vigneshshanmugam** [comment]
Fixes #10

**Comment by rmurphey** [comment]
Thanks for this! I'll give it a try in the next day or so, but it looks great. Really appreciate it.

**Comment by vigneshshanmugam** [comment]
:+1:

**Comment by vigneshshanmugam** [comment]
@rmurphey Is this fine or do you want me to change anything?

**Pull request closed without merging**
